# Generated by Django 5.0 on 2024-01-05 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garnelmath', '0003_feedback_subscribe_alter_post_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribe',
            new_name='Subscription',
        ),
    ]
