# Generated by Django 5.0 on 2024-01-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garnelmath', '0005_alter_subscription_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(verbose_name='feedback'),
        ),
    ]
