# Generated by Django 5.0 on 2024-01-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garnelmath', '0006_alter_feedback_feedback'),
    ]

